//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCaFe_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeCaFe_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0cfe554dc844bd0055f2ae585fd6d849 {
            get {
                object obj = ResourceManager.GetObject("0cfe554dc844bd0055f2ae585fd6d849", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0cfe554dc844bd0055f2ae585fd6d849__1_ {
            get {
                object obj = ResourceManager.GetObject("0cfe554dc844bd0055f2ae585fd6d849 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0cfe554dc844bd0055f2ae585fd6d849__1___1_ {
            get {
                object obj = ResourceManager.GetObject("0cfe554dc844bd0055f2ae585fd6d849 (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgf {
            get {
                object obj = ResourceManager.GetObject("bgf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgg {
            get {
                object obj = ResourceManager.GetObject("bgg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgj {
            get {
                object obj = ResourceManager.GetObject("bgj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgk {
            get {
                object obj = ResourceManager.GetObject("bgk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgm {
            get {
                object obj = ResourceManager.GetObject("bgm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffe_time_18591_34563 {
            get {
                object obj = ResourceManager.GetObject("coffe-time_18591-34563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_banner_realistic_coffee_beans_illustration_190024_127 {
            get {
                object obj = ResourceManager.GetObject("coffee-banner-realistic-coffee-beans-illustration_190024-127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_beans_background_1756_449 {
            get {
                object obj = ResourceManager.GetObject("coffee-beans-background_1756-449", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_beans_with_props_making_coffee_1220_4536 {
            get {
                object obj = ResourceManager.GetObject("coffee-beans-with-props-making-coffee_1220-4536", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_beans_with_props_making_coffee_1220_4536__1_ {
            get {
                object obj = ResourceManager.GetObject("coffee-beans-with-props-making-coffee_1220-4536 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_beans_with_props_making_coffee_1220_4536__1___1_ {
            get {
                object obj = ResourceManager.GetObject("coffee-beans-with-props-making-coffee_1220-4536 (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_concept_white_background_white_coffee_cup_top_view_with_watercolor_coffee_splashes_hand_draw_watercolor_coffee_illustration_with_beautiful_art_splashes_165217_7 {
            get {
                object obj = ResourceManager.GetObject("coffee-concept-white-background-white-coffee-cup-top-view-with-watercolor-coffee-" +
                        "splashes-hand-draw-watercolor-coffee-illustration-with-beautiful-art-splashes_16" +
                        "5217-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_poster_advertisement_flayers_73621_868 {
            get {
                object obj = ResourceManager.GetObject("coffee-poster-advertisement-flayers_73621-868", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_poster_advertisement_flayers_vector_illustration_73621_544 {
            get {
                object obj = ResourceManager.GetObject("coffee-poster-advertisement-flayers-vector-illustration_73621-544", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_shop_neon_logo_75817_953 {
            get {
                object obj = ResourceManager.GetObject("coffee-shop-neon-logo_75817-953", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffet_time_24877_6619 {
            get {
                object obj = ResourceManager.GetObject("coffet-time_24877-6619", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cup_coffee_with_coffee_beans_wooden_background_43605_2933 {
            get {
                object obj = ResourceManager.GetObject("cup-coffee-with-coffee-beans-wooden-background_43605-2933", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decorative_coffee_beans_leaves_seamless_pattern_suitable_wrapping_paper_2482_402 {
            get {
                object obj = ResourceManager.GetObject("decorative-coffee-beans-leaves-seamless-pattern-suitable-wrapping-paper_2482-402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_drawn_coffee_drink_background_52683_16134 {
            get {
                object obj = ResourceManager.GetObject("hand-drawn-coffee-drink-background_52683-16134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hot_espresso_coffee_bean_white_table_41050_2106 {
            get {
                object obj = ResourceManager.GetObject("hot-espresso-coffee-bean-white-table_41050-2106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap llll {
            get {
                object obj = ResourceManager.GetObject("llll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap morning_cup_coffee_with_spoon_love_sign_vector_clip_art_illustration_138676_101 {
            get {
                object obj = ResourceManager.GetObject("morning-cup-coffee-with-spoon-love-sign-vector-clip-art-illustration_138676-101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oo {
            get {
                object obj = ResourceManager.GetObject("oo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ppp {
            get {
                object obj = ResourceManager.GetObject("ppp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap realistic_white_with_black_coffee_1284_2029 {
            get {
                object obj = ResourceManager.GetObject("realistic-white-with-black-coffee_1284-2029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seamless_pattern_with_coffee_sweet_coffee_background_87506_756 {
            get {
                object obj = ResourceManager.GetObject("seamless-pattern-with-coffee-sweet-coffee-background_87506-756", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_coffee_accessories_with_beans_23_2148336723 {
            get {
                object obj = ResourceManager.GetObject("top-view-coffee-accessories-with-beans_23-2148336723", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_copy_space_23_2148336691 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-copy-space_23-2148336691", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_copy_space_23_2148336753 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-copy-space_23-2148336753", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_roasted_beans_52683_32340 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-roasted-beans_52683-32340", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_roasted_beans_52683_32340__1_ {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-roasted-beans_52683-32340 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_roasted_beans_52683_32340__1_1 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-roasted-beans_52683-32340 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_roasted_beans_52683_323401 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-roasted-beans_52683-323401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_coffee_with_roasted_beans_52683_323402 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-coffee-with-roasted-beans_52683-323402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_cup_fresh_black_coffee_52683_32341 {
            get {
                object obj = ResourceManager.GetObject("top-view-cup-fresh-black-coffee_52683-32341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vintage_hand_drawn_illustration_coffee_grinder_with_croissant_breakfast_concept_1441_1929 {
            get {
                object obj = ResourceManager.GetObject("vintage-hand-drawn-illustration-coffee-grinder-with-croissant-breakfast-concept_1" +
                        "441-1929", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
